substitutions:
  _REGION: us-central1
  _TEAM: team-data-engineers
  _TARGET_PROJECT_ID: amoros-sandbox-344216
  _CLOUDSDK_CONTAINER_CLUSTER: krmapihost-config-controller-bc
steps:
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=team-data-engineers/dev
  - --location=${_REGION}
  - --cluster=${_CLOUDSDK_CONTAINER_CLUSTER}

- name: 'google/cloud-sdk:latest'
  entrypoint: 'sh'
  args:
  - -xe
  - -c
  - |
    gcloud config set deploy/region ${_REGION}
    gcloud container clusters get-credentials ${_CLOUDSDK_CONTAINER_CLUSTER} --region ${_REGION}
    kubectl delete -f team-data-engineers/dev

- name: gcr.io/k8s-skaffold/skaffold
  args:
    - skaffold
    - build
    - '--interactive=false'
    - '--file-output=/workspace/artifacts.json'
  
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: gcloud
  args:
    [
      "deploy", "releases", "create", "rel-${SHORT_SHA}",
      "--delivery-pipeline", "cicd-pipeline",
      "--region", "us-central1",
      "--annotations", "commitId=${REVISION_ID}",
      "--build-artifacts", "/workspace/artifacts.json"
    ]

# steps:
# - name: gcr.io/cloud-builders/gke-deploy
#   args:
#   - run
#   - --filename=resources/
#   - --location=us-central1
#   - --cluster=krmapihost-config-controller-bc

# - name: 'gcr.io/cloud-builders/kubectl'
#   args: ['delete', '-f', 'resources/'  ]
#   env:
#   - 'CLOUDSDK_COMPUTE_ZONE=us-central1'
#   - 'CLOUDSDK_CONTAINER_CLUSTER=krmapihost-config-controller-bc'



# # Promote to staging
# - name: gcr.io/google.com/cloudsdktool/cloud-sdk
#   entrypoint: gcloud
#   args: 
#     [
#       "deploy", "releases", "promote", 'rel-${COMMIT_SHA}' ,
#       "--delivery-pipeline", "cicd-pipeline",
#       "--region", "us-central1",
#     ] 







