steps:
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'bigquery-datasets/bq.yaml', 'bigquery-datasets/buckets.yaml' ]
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=krmapihost-config-controller-bc'
