apiVersion: skaffold/v2beta16
kind: Config
profiles:
 - name: prod
   deploy:
     kubectl:
       manifests:
         - team-data-engineers/prod/*
 - name: staging
   deploy:
     kubectl:
       manifests:
         - team-data-engineers/staging/*
