apiVersion: skaffold/v2beta16
kind: Config
metadata:
 name: getting-started-kustomize

deploy:
  kubectl:
    manifests:
      - team-data-engineers/dev
profiles:
- name: staging
  deploy:
    kubectl:
      manifests:
        - team-data-engineers/staging
- name: prod
  deploy:
    kubectl:
      manifests:
        - team-data-engineers/prod




