apiVersion: skaffold/v2beta16
kind: Config
metadata:
 name: getting-started-kustomize

deploy:
  kubectl:
    manifests:
      - team-data-engineers/dev/buckets-dev.yaml
profiles:
- name: staging
  deploy:
    kubectl:
      manifests:
        - team-data-engineers/staging/buckets-staging.yaml
- name: prod
  deploy:
    kubectl:
      manifests:
        - team-data-engineers/prod.buckets-prod.yaml




