apiVersion: skaffold/v2beta16
kind: Config
deploy:
  kubectl:
    manifests:
      - team-data-engineers/staging/*

profiles:
- name: prod
  deploy:
    kubectl:
      manifests:
      - team-data-engineers/prod/*
