substitutions:
  _REGION: us-central1
  _TEAM: team-data-engineers
  _TARGET_PROJECT_ID: amoros-sandbox-344216
  _CLOUDSDK_CONTAINER_CLUSTER: krmapihost-config-controller-bc

#Var substitutions
steps:
# - name: 'google/cloud-sdk:latest'
#   entrypoint: 'sh'
#   args:
#   - -xe
#   - -c
#   - |
#     gcloud config set deploy/region ${_REGION} 
#     sed -i s/PROJECT_ID/$PROJECT_ID/g ${_TEAM}/resources/dev/*

#Deploy Resources
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=team-data-engineers/resources/dev
  - --location=${_REGION}
  - --cluster=${_CLOUDSDK_CONTAINER_CLUSTER}

#Delete the resources we created
- name: 'google/cloud-sdk:latest'
  entrypoint: 'sh'
  args:
  - -xe
  - -c
  - |
    gcloud config set deploy/region ${_REGION}
    gcloud container clusters get-credentials ${_CLOUDSDK_CONTAINER_CLUSTER} --region ${_REGION}
    kubectl delete -f team-data-engineers/resources/dev
  








