apiVersion: skaffold/v2beta16
kind: Config
metadata:
 name: getting-started-kustomize
deploy:
  kubectl:
    manifests:
      - resources/dev/buckets-dev.yaml
profiles:
- name: staging
  deploy:
    kubectl:
      manifests:
        - resources/staging/buckets-staging.yaml
- name: prod
  deploy:
    kubectl:
      manifests:
        - resources/prod/buckets-prod.yaml


