apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
 name: cicd-pipeline
description: main application pipeline
serialPipeline:
 stages:
 - targetId: staging
   profiles: []
 - targetId: prod
   profiles: []
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: staging
description: staging cluster
gke:
 cluster: projects/amoros-sandbox-344216/locations/us-central1/clusters/krmapihost-config-controller-bc
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: prod
description: production cluster
gke:
 cluster: projects/amoros-sandbox-344216/locations/us-central1/clusters/krmapihost-config-controller-bc